### ISSUE TITLE
update vm1's db to current

### ISSUE THREAD

**Issue by hexmode** [wikipathways/wikipathways-upgrade-2015#24]
please? @AlexanderPico ?

**Comment by AlexanderPico** [comment]
I can do that!  Will get to it later today...

**Comment by AlexanderPico** [comment]
Performed these steps:
1. obtain sql dump from production
2. log into vm1; log into mysql
3. source sql dump file
4. run maintenance/update.php

The script complained about a few lines in LocalSettings.php

PHP Notice:  Undefined index: HTTP_HOST in /var/www/wikipathways/w/LocalSettings.php on line 439
PHP Stack trace:
PHP   1. {main}() /var/www/wikipathways/w/maintenance/update.php:0
PHP   2. require_once() /var/www/wikipathways/w/maintenance/update.php:192
PHP   3. require() /var/www/wikipathways/w/maintenance/doMaintenance.php:88

Otherwise, ran without errors and vm1 loads, BUT... It's missing uploaded images (front page) and thumbnails (e.g., browse page) and pathway pages are blank....

DID I MESS IT UP??

**Comment by hexmode** [comment]
Alexander Pico writes:

> The script complained about a few lines in LocalSettings.php
> 
> PHP Notice:  Undefined index: HTTP_HOST in /var/www/wikipathways/w/LocalSettings.php on line 439
> PHP Stack trace:
> PHP   1. {main}() /var/www/wikipathways/w/maintenance/update.php:0
> PHP   2. require_once() /var/www/wikipathways/w/maintenance/update.php:192
> PHP   3. require() /var/www/wikipathways/w/maintenance/doMaintenance.php:88

I'd love to get these fixed.  If you have any others, please create
issues for them.

> Otherwise, ran without errors and vm1 loads, BUT... It's missing uploaded images (front page) and thumbnails (e.g., browse page) and pathway pages are blank....
> 
> DID I MESS IT UP??

No, its fine.  I think we can just use rsync on the images subdirectory
for the rest.  If you want to do that, you can.  Otherwise, let me know
and I'll handle it.

Thanks!

## 

Mark A. Hershberger
NicheWork LLC
717-271-1084

**Comment by AlexanderPico** [comment]
Those were the only 3 php notices.

I've set a scp going in a screen session. I'm heading out of town now, so I hope that fixes the images. If not, I'll have to ask you to give it a shot (sorry!)

**Comment by hexmode** [comment]
Looks like this is done.  I had to chown the images directory and all subdirs to www-data, though.
